name: Build and Push Docker Image to ECR
on:
  push:
    branches: [ main ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build Docker image
        run: docker build -t aems:latest .
      - name: Tag Docker image
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/aems:latest"
          docker tag aems:latest $IMAGE_URI
      - name: Push Docker image to ECR
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/aems:latest"
          docker push $IMAGE_URI

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push   # waits for image to be pushed
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Force ECS redeploy
        run: |
          aws ecs update-service \
            --cluster your-cluster-name \
            --service your-service-name \
            --force-new-deployment